source 'http://rubygems.org'

gem 'rails', '3.2.12'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'mysql2'
gem 'git'
gem 'execjs'
gem 'css3-progress-bar-rails'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
   gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'rake', '10.1.1'
gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
group :development do
  gem 'pry-rails'
  gem 'pry-nav'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'capybara'#, :git => 'git://github.com/jnicklas/capybara.git'
  gem 'launchy'
  gem 'rb-fsevent'
  gem 'guard-rspec'
  gem 'guard-bundler'
  gem 'guard-livereload'
  gem 'fog'
  gem 'jenkins_api_client'
  gem 'xml-simple'
  gem 'bootstrap-sass', '2.2.1.1'
  #gem 'database_cleaner'
end

gem 'bootstrap-sass', '2.2.1.1'
gem 'passenger'
gem 'github_api'
gem 'scoped_choices'
